return {{[ [[AK V8.5]] ] = {2},[ [[Basher]] ] = {3},[ [[Legacy GUI]] ] = {4},[ [[Trades]] ] = {5},[ [[Shrine Tracker]] ] = {6},[ [[Mudlet Mapper]] ] = {7},[ [[Curing Swaps]] ] = {8},[ [[Limb Tracker]] ] = {9},[ [[Soundtrack]] ] = {10},},
{[ [[link]] ] = [[https://github.com/AranosBanazir/Legacy/raw/main/AK.xml]],[ [[desc]] ] = [[Austere's Affliction Tracking.]],},
{[ [[link]] ] = [[https://github.com/Legacy-System/Legacy/raw/main/Basher.mpackage]],[ [[desc]] ] = [[Bashing Package V2.1.]],},
{[ [[link]] ] = [[https://github.com/Legacy-System/Legacy/raw/main/Legacy%20UI.mpackage]],[ [[desc]] ] = [[Legacy GUI V2.0]],},
{[ [[link]] ] = [[https://github.com/Legacy-System/Legacy/raw/main/Trades.mpackage]],[ [[desc]] ] = [[Legacy Trades Package for: Conjuration, Inkmilling, Augmentation]],},
{[ [[link]] ] = [[https://github.com/Legacy-System/Legacy/raw/main/Shrines%20V3.0.mpackage]],[ [[desc]] ] = [[Package to track, display, and autowalk to shrines.]],},
{[ [[link]] ] = [[https://ire-mudlet-mapping.github.io/ire-mapping-script/downloads/mudlet-mapper.xml]],[ [[desc]] ] = [[Mudlet Mapper for Achaea.]],},
{[ [[link]] ] = [[https://github.com/Legacy-System/Legacy/raw/main/Curing%20Swaps.xml]],[ [[desc]] ] = [[Curing Swap function, downloading it through extras will allow you to keep it between updates of Legacy.]],},
{[ [[link]] ] = [[https://github.com/27theo/limb/releases/download/v1.3/limb.1.3.mpackage]],[ [[desc]] ] = [[Romaen's Limb tracker V1.3]],},
{[ [[link]] ] = [[https://github.com/MegophrysNasuta/SOUNDTRACK/raw/main/SOUNDTRACK.mpackage]],[ [[desc]] ] = [[Nasuta's Ambient Soundtracks, changes based on environments]],},
}
